#!/usr/bin/env bash

# ============================================================================
# SEEDBAY QUICK START GUIDE
# 28 janvier 2026
# ============================================================================

echo "════════════════════════════════════════════════════════════════════"
echo "🚀 SEEDBAY - QUICK START GUIDE"
echo "════════════════════════════════════════════════════════════════════"
echo ""

# COLORS
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 FICHIERS DISPONIBLES:${NC}"
echo ""
echo -e "${GREEN}▶ DOCUMENTATION COMPLÈTE (Lire dans cet ordre):${NC}"
echo "  1. SEEDBAY-README.md                  ⭐ START HERE (20 min)"
echo "  2. LIVRABLES-INDEX.md                 Index des fichiers (20 min)"
echo "  3. POINTS-CRITIQUES.md                Checklist sécurité (15 min)"
echo "  4. seedbay-auth-security.js           Flows & menaces (30 min)"
echo "  5. seedbay-executive-summary.ts       Architecture (30 min)"
echo "  6. seedbay-security.sql               Schema SQL (45 min)"
echo "  7. seedbay-deployment-guide.ts        Deployment (45 min)"
echo "  8. seedbay-threats-roadmap.ts         Risques & roadmap (30 min)"
echo ""

echo -e "${GREEN}▶ CODE SOURCE À UTILISER (Copy-paste dans votre projet):${NC}"
echo "  9.  seedbay-middleware.ts             → src/middleware.ts"
echo " 10.  seedbay-auth-lib.ts               → src/lib/auth.ts"
echo " 11.  seedbay-signup-route.ts           → src/app/api/auth/signup/route.ts"
echo " 12.  seedbay-create-order-route.ts     → src/app/api/orders/create-intent/route.ts"
echo " 13.  seedbay-webhook-route.ts          → src/app/api/payments/webhook/route.ts ⚠️"
echo ""

echo -e "${GREEN}▶ TESTS DE SÉCURITÉ:${NC}"
echo " 14.  seedbay-security-tests.ts         56 test cases (30 min)"
echo ""

echo "════════════════════════════════════════════════════════════════════"
echo ""

# Menu interactif
echo -e "${YELLOW}Que voulez-vous faire?${NC}"
echo ""
echo "1) 📖  Lire la documentation"
echo "2) 💻 Implémenter le code"
echo "3) 🧪 Tester la sécurité"
echo "4) 🚀 Déployer en production"
echo "5) 📋 Voir la checklist complète"
echo "6) ❌ Quitter"
echo ""
read -p "Choisissez (1-6): " choice

case $choice in
  1)
    echo ""
    echo -e "${BLUE}📖 PHASE 1: DOCUMENTATION${NC}"
    echo ""
    echo "Lire dans cet ordre (2-3 heures):"
    echo ""
    echo -e "${GREEN}1. SEEDBAY-README.md${NC}"
    echo "   └─ Vue d'ensemble, architecture, checklist"
    echo ""
    echo -e "${GREEN}2. POINTS-CRITIQUES.md${NC}"
    echo "   └─ Points à NE PAS OUBLIER"
    echo ""
    echo -e "${GREEN}3. seedbay-auth-security.js${NC}"
    echo "   └─ Flows d'authentification, menaces, défenses"
    echo ""
    echo -e "${GREEN}4. seedbay-executive-summary.ts${NC}"
    echo "   └─ Architecture technique détaillée"
    echo ""
    echo -e "${GREEN}5. seedbay-deployment-guide.ts${NC}"
    echo "   └─ Comment déployer en production"
    echo ""
    echo "Après avoir lu: passez à l'étape 2 (Implémenter)"
    echo ""
    ;;
  2)
    echo ""
    echo -e "${BLUE}💻 PHASE 2: IMPLÉMENTATION (1 SEMAINE)${NC}"
    echo ""
    echo -e "${GREEN}JOUR 1-2: Setup Infrastructure${NC}"
    echo "  1. Créer un projet Supabase (https://supabase.com)"
    echo "  2. Créer un compte Stripe (https://stripe.com)"
    echo "  3. Créer un projet Vercel (https://vercel.com)"
    echo "  4. Créer un repo Git (GitHub)"
    echo ""
    echo -e "${GREEN}JOUR 2: Exécuter le Schema SQL${NC}"
    echo "  1. Copier le contenu de seedbay-security.sql"
    echo "  2. Aller sur Supabase → SQL Editor"
    echo "  3. Coller et exécuter (🟢 APPLY)"
    echo "  4. Vérifier que RLS est activé:"
    echo "     SELECT * FROM information_schema.tables"
    echo "     WHERE row_security_level IS NOT NULL"
    echo ""
    echo -e "${GREEN}JOUR 3: Copier le Code Source${NC}"
    echo "  1. Initialiser Next.js project: npx create-next-app@latest"
    echo "  2. Installer dépendances:"
    echo "     npm install @supabase/supabase-js stripe zod jose"
    echo ""
    echo "  3. Copier les fichiers:"
    echo "     - seedbay-middleware.ts → src/middleware.ts"
    echo "     - seedbay-auth-lib.ts → src/lib/auth.ts"
    echo "     - seedbay-signup-route.ts → src/app/api/auth/signup/route.ts"
    echo "     - seedbay-create-order-route.ts → src/app/api/orders/create-intent/route.ts"
    echo "     - seedbay-webhook-route.ts → src/app/api/payments/webhook/route.ts"
    echo ""
    echo "  4. Configurer .env:"
    echo "     NEXT_PUBLIC_SUPABASE_URL=https://[project].supabase.co"
    echo "     NEXT_PUBLIC_SUPABASE_ANON_KEY=[anon-key]"
    echo "     SUPABASE_JWT_SECRET=[jwt-secret]"
    echo "     STRIPE_SECRET_KEY=<stripe-secret>"
    echo "     STRIPE_WEBHOOK_SECRET=<stripe-webhook-secret>"
    echo ""
    echo -e "${GREEN}JOUR 4-5: Frontend Pages${NC}"
    echo "  - Page d'accueil"
    echo "  - Marketplace (listing des projets)"
    echo "  - Détail d'un projet"
    echo "  - Checkout (Stripe Elements)"
    echo "  - Dashboard vendeur"
    echo "  - Dashboard acheteur"
    echo ""
    echo -e "${GREEN}JOUR 6: Tester${NC}"
    echo "  - npm run test:security (56 test cases)"
    echo "  - Vérifier tous les tests passent"
    echo ""
    echo -e "${GREEN}JOUR 7: Déployer${NC}"
    echo "  - Staging deployment sur Vercel"
    echo "  - Tests finaux"
    echo "  - Production deployment"
    echo ""
    ;;
  3)
    echo ""
    echo -e "${BLUE}🧪 PHASE 3: TESTS DE SÉCURITÉ${NC}"
    echo ""
    echo "Avant production, tester les 56 cas:"
    echo ""
    echo -e "${GREEN}1. AUTHENTICATION (6 tests)${NC}"
    echo "   - Signup avec email invalide"
    echo "   - Signup avec password faible"
    echo "   - Email verification flow"
    echo "   - Login incorrect"
    echo "   - JWT expiration"
    echo "   - JWT modification"
    echo ""
    echo -e "${GREEN}2. AUTHORIZATION (7 tests)${NC}"
    echo "   - Buyer voir projets publiés"
    echo "   - Vendor voir ses projets"
    echo "   - Admin voir tous les projets"
    echo "   - Vendor ne peut pas éditer projet d'autres"
    echo "   - Etc."
    echo ""
    echo -e "${GREEN}3. PAYMENTS (10 tests)${NC}"
    echo "   - Créer commande"
    echo "   - Email verification required"
    echo "   - Achat unique"
    echo "   - Webhook forgery"
    echo "   - Montant vérifié"
    echo "   - Etc."
    echo ""
    echo -e "${GREEN}4. FILES (8 tests)${NC}"
    echo "   - Owner voir fichiers"
    echo "   - Buyer non-propriétaire = pas d'accès"
    echo "   - Signed URL expiration"
    echo "   - Etc."
    echo ""
    echo "Voir seedbay-security-tests.ts pour tous les tests"
    echo ""
    echo -e "${YELLOW}⚠️  TOUS LES TESTS DOIVENT PASSER AVANT PRODUCTION!${NC}"
    echo ""
    ;;
  4)
    echo ""
    echo -e "${BLUE}🚀 PHASE 4: DÉPLOIEMENT PRODUCTION${NC}"
    echo ""
    echo -e "${GREEN}JOUR 1: Pré-déploiement${NC}"
    echo "  ✓ Lire seedbay-deployment-guide.ts complètement"
    echo "  ✓ Vérifier checklist sécurité"
    echo "  ✓ Database backups créé"
    echo "  ✓ Stripe webhook configuré"
    echo "  ✓ Vercel environment variables OK"
    echo ""
    echo -e "${GREEN}JOUR 2: Staging${NC}"
    echo "  1. Créer Vercel preview deployment"
    echo "  2. Tester transaction complète"
    echo "  3. Tester avec Stripe test keys"
    echo "  4. Monitorer logs pendant 2h"
    echo ""
    echo -e "${GREEN}JOUR 3: Production${NC}"
    echo "  1. Git push → Vercel auto-deploys (~2 min)"
    echo "  2. Vérifier health endpoint"
    echo "  3. Tester critical paths"
    echo "  4. Monitorer Sentry + logs"
    echo ""
    echo -e "${GREEN}JOUR 4+: Monitoring${NC}"
    echo "  - Vérifier paiements complétés"
    echo "  - Vérifier downloads fonctionnent"
    echo "  - Analyser metrics de performance"
    echo "  - Prêt pour marketing!"
    echo ""
    echo -e "${YELLOW}CHECKLIST FINALE:${NC}"
    echo "  [ ] Tous les 56 tests PASSED"
    echo "  [ ] Aucun error dans Sentry"
    echo "  [ ] Performance < 200ms p99"
    echo "  [ ] Uptime 100% pendant 24h"
    echo "  [ ] 10+ transactions réussies"
    echo "  [ ] Monitoring configuré"
    echo ""
    echo -e "${GREEN}✅ Vous êtes prêt à lancer!${NC}"
    echo ""
    ;;
  5)
    echo ""
    echo -e "${BLUE}📋 CHECKLIST COMPLÈTE${NC}"
    echo ""
    echo -e "${YELLOW}SÉCURITÉ (CRITICAL):${NC}"
    echo "  [ ] Lire POINTS-CRITIQUES.md"
    echo "  [ ] Aucun secret en plaintext"
    echo "  [ ] .env.local dans .gitignore"
    echo "  [ ] RLS activé sur TOUTES les tables"
    echo "  [ ] Webhook Stripe signature validée"
    echo "  [ ] SELECT seulement colonnes nécessaires"
    echo "  [ ] Zod validation sur tous les POST/PATCH"
    echo ""
    echo -e "${YELLOW}DATABASE:${NC}"
    echo "  [ ] SQL schema exécuté"
    echo "  [ ] Backups configurés (daily)"
    echo "  [ ] Connection pooling setup"
    echo "  [ ] RLS policies testées"
    echo ""
    echo -e "${YELLOW}STRIPE:${NC}"
    echo "  [ ] Compte production créé"
    echo "  [ ] 2FA activée"
    echo "  [ ] Webhook configuré + secret copié"
    echo "  [ ] Test webhook: stripe trigger"
    echo ""
    echo -e "${YELLOW}FRONTEND:${NC}"
    echo "  [ ] Helmet.js pour headers"
    echo "  [ ] CORS configuré"
    echo "  [ ] CSP header"
    echo "  [ ] HTTPS enforced"
    echo ""
    echo -e "${YELLOW}MONITORING:${NC}"
    echo "  [ ] Sentry intégré"
    echo "  [ ] Alertes configurées"
    echo "  [ ] Logs queryable"
    echo ""
    echo -e "${YELLOW}TESTING:${NC}"
    echo "  [ ] 56/56 tests passed"
    echo "  [ ] Load testing OK"
    echo "  [ ] Security audit OK"
    echo ""
    ;;
  6)
    echo ""
    echo -e "${GREEN}À bientôt! 👋${NC}"
    echo ""
    exit 0
    ;;
  *)
    echo -e "${RED}Option invalide${NC}"
    ;;
esac

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo -e "${GREEN}✅ SEEDBAY EST PRÊT POUR ÊTRE LANCÉ!${NC}"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "🎯 NEXT STEPS:"
echo "  1. Lire SEEDBAY-README.md"
echo "  2. Suivre les phases d'implémentation"
echo "  3. Tester avec les 56 security test cases"
echo "  4. Déployer en production"
echo ""
echo "📞 Si besoin d'aide:"
echo "  - Relire la documentation pertinente"
echo "  - Vérifier les points critiques dans POINTS-CRITIQUES.md"
echo "  - Checker la checklist dans seedbay-deployment-guide.ts"
echo ""
echo "🚀 BON DÉVELOPPEMENT!"
echo ""
